package org.example.Service;


import java.util.List;
import org.example.Model.ProjectDocument;
import org.example.Repository.ProjectDocumentRepository;

public class ProjectDocumentService {

    private final ProjectDocumentRepository documentRepository;

    public ProjectDocumentService() {
        this.documentRepository = new ProjectDocumentRepository();
    }

    /**
     * Uploads a document for a project.
     */
    public void uploadDocument(String projectId, String fileName, String fileType, byte[] fileData) {
        // documentId will be auto-generated by DB trigger
        ProjectDocument document = new ProjectDocument();
        document.setProjectId(projectId);
        document.setFileName(fileName);
        document.setFileType(fileType);
        document.setFileData(fileData);

        documentRepository.uploadDocument(document);
    }

    public boolean projectExists(String projectId) {
        return documentRepository.projectExists(projectId);
    }


    /**
     * Fetches a specific document by document ID.
     */
    public ProjectDocument getDocumentById(String documentId) {
        return documentRepository.getDocumentById(documentId);
    }

    /**
     * Fetches all documents attached to a specific project.
     */
    public List<ProjectDocument> getDocumentsByProjectId(String projectId) {
        return documentRepository.getDocumentsByProjectId(projectId);
    }

    /**
     * Deletes a document by its document ID.
     */
    public boolean deleteDocument(String documentId) {
        return documentRepository.deleteDocument(documentId);
    }
}
